### ISSUE TITLE
locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by ghost** [udoprog/c10t#203]
Tried to run the latest stable build and got this error:

[username@computername c10t]$ ./c10t --help
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Keskeytetty

("Keskeytetty") is Finnish for "Interrupted" or something...

All dependencies should be OK.

I tried to run with --debug but it gave the same error, as well as --version.

**Comment by snailshen2014** [comment]
I hava the same issue on debian

**Comment by evildeeds** [comment]
This appears to be a five years old upstream bug with libboost, either update your system or try one of the suggested workarounds and if thats not the problem then open a new bug.

As suggested in this issue you may wish to ensure that;
Your system is updated.
LC_* envs are correctly set.
System is configured to use unicode and UTF-8.
Selected locale actually exists or (re-)create english locale by running 'locale-gen en_US.UTF-8'.

Since this is not actually c10t's fault, other then that libboost is used, I'm locking this to prevent futher necroing.
