### ISSUE TITLE
Getting error 'Image height exceeds user limit in IHDR'

### ISSUE THREAD

**Issue by nonvwvnon** [udoprog/c10t#267]
I am on the 64 bit linux server.

i couldn't find image.cpp as mention in another ticket - https://github.com/udoprog/c10t/issues/59

how do we increase the limit?

care to give more details how to fix it.

thanks alot.

Error message:

libpng warning: Image width exceeds user limit in IHDR
libpng warning: Image height exceeds user limit in IHDR
libpng warning: Invalid image width in IHDR
libpng warning: Invalid image height in IHDR
libpng warning: Width is too large for libpng to process pixels
libpng error: Invalid IHDR data

**Comment by arjunyg** [comment]
um this is still an issue?

**Comment by evildeeds** [comment]
It has been some time since I last looked into this project, however this issue looks to me like misuse of libpng and c10t seems to have ignored the png size limitations set by the png standard itself (according to the [specification](http://libpng.org/pub/png/spec/1.2/PNG-Chunks.html) it should be "2^31").

A quick look at [generate_map.cpp#L682](https://github.com/udoprog/c10t/blob/master/src/generate_map.cpp#L682), [png.hpp#L21](https://github.com/udoprog/c10t/blob/master/src/image/format/png.hpp#L21) and [image_base.hpp#L23 ](https://github.com/udoprog/c10t/blob/master/src/image/image_base.hpp#L23) suggest that similar issues may still be possible to trigger.

However the way other size issues where resolved was to default the maximum radius [-R](https://github.com/udoprog/c10t/blob/master/src/main.cpp#L127) parameter to 1000, ensuring that a resulting image has a guaranteed size limit, of course to render other areas outside of this radius you would have to specify [--center](https://github.com/udoprog/c10t/blob/master/src/main.cpp#L131), or even using [-L](https://github.com/udoprog/c10t/blob/master/src/main.cpp#L121) to slice the resulting world image into multiple images. Additionally I have personally not seen any libpng issues on any of my own worlds as far as I can remember and those are not that small either but you know, not as large as a public server could be expected to be but whatever...

I would suggest that if you manage to trigger a pnglib issue you open a new ticket, perhaps referencing this post and #59 depending on the cause.

**Comment by B-Yassine** [comment]
i am having the same issue: 
libpng warning: Invalid image width in IHDR
libpng warning: Image width exceeds user limit in IHDR
libpng warning: Invalid image height in IHDR
libpng warning: Image height exceeds user limit in IHDR
libpng error: Invalid IHDR data
libpng warning: Invalid image width in IHDR
libpng warning: Image width exceeds user limit in IHDR
libpng warning: Invalid image height in IHDR
libpng warning: Image height exceeds user limit in IHDR
libpng error: Invalid IHDR data

**Comment by evildeeds** [comment]
@B-Yassine Sorry for the late answer, please open a new issue instead as I suggest in my previous post and include your command line and the version of c10t or more likely the git commit you used to compile c10t since I don't think there is a binary release that is up to date available.
